# Generated by Django 6.0.7 on 2026-08-10 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matrimonio',
            fields=[
                ('id_matrimonio', models.AutoField(db_column='id_matrimonio', primary_key=True, serialize=False)),
                ('fecha_matrimonio', models.DateField()),
            ],
            options={
                'verbose_name': 'Matrimonio',
                'verbose_name_plural': 'Matrimonios',
                'db_table': 'matrimonios',
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id_estudiante', models.AutoField(db_column='id_estudiante', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('genero', models.CharField(choices=[('MASCULINO', 'Masculino'), ('FEMENINO', 'Femenino')], max_length=10)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('fecha_bautismo', models.DateField(blank=True, null=True)),
                ('fecha_inicio_servicio_tiempo_completo', models.DateField(blank=True, null=True)),
                ('matrimonio', models.ForeignKey(blank=True, db_column='id_matrimonio', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudiantes', to='estudiantes.matrimonio')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'db_table': 'estudiantes',
            },
        ),
    ]
