# Generated by Django 6.0.7 on 2026-08-25 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Responsabilidad',
            fields=[
                ('id_responsabilidad', models.AutoField(db_column='id_responsabilidad', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Responsabilidad',
                'verbose_name_plural': 'Responsabilidades',
                'db_table': 'responsabilidades',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='estudiante',
            name='responsabilidades',
            field=models.ManyToManyField(blank=True, db_table='estudiantes_responsabilidades', related_name='estudiantes', to='estudiantes.responsabilidad'),
        ),
    ]
