# Generated by Django 6.0.7 on 2026-08-27 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0003_cargar_responsabilidades_iniciales'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsabilidad',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
