# Generated by Django 6.0.7 on 2026-08-27 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0001_initial'),
        ('docencia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoRecordatorio',
            fields=[
                ('id_tipo', models.AutoField(db_column='id_tipo', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(choices=[('AZUL', 'Azul'), ('VERDE', 'Verde'), ('AMBAR', 'Ámbar'), ('ROJO', 'Rojo'), ('VIOLETA', 'Violeta'), ('GRIS', 'Gris')], default='GRIS', max_length=10)),
            ],
            options={
                'verbose_name': 'Tipo de recordatorio',
                'verbose_name_plural': 'Tipos de recordatorio',
                'db_table': 'tipos_recordatorio',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Recordatorio',
            fields=[
                ('id_recordatorio', models.AutoField(db_column='id_recordatorio', primary_key=True, serialize=False)),
                ('numero_semana', models.PositiveSmallIntegerField()),
                ('fecha', models.DateField()),
                ('hora', models.TimeField(blank=True, null=True)),
                ('descripcion', models.CharField(max_length=255)),
                ('completado', models.BooleanField(default=False)),
                ('clase', models.ForeignKey(db_column='id_clase', on_delete=django.db.models.deletion.CASCADE, related_name='recordatorios', to='academico.clase')),
                ('responsables', models.ManyToManyField(blank=True, db_table='recordatorios_responsables', related_name='recordatorios', to='docencia.instructor')),
                ('tipo', models.ForeignKey(db_column='id_tipo', on_delete=django.db.models.deletion.PROTECT, related_name='recordatorios', to='recordatorios.tiporecordatorio')),
            ],
            options={
                'verbose_name': 'Recordatorio',
                'verbose_name_plural': 'Recordatorios',
                'db_table': 'recordatorios',
                'ordering': ['numero_semana', 'fecha', models.OrderBy(models.F('hora'), nulls_last=True)],
            },
        ),
    ]
