# Generated by Django 6.0.7 on 2026-08-10 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0001_initial'),
        ('docencia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramacionClase',
            fields=[
                ('id_programacion', models.AutoField(db_column='id_programacion', primary_key=True, serialize=False)),
                ('codigo_clase', models.CharField(max_length=10)),
                ('numero_semana', models.PositiveSmallIntegerField()),
                ('dia_semana', models.CharField(max_length=20)),
                ('numero_aula', models.PositiveSmallIntegerField()),
                ('clase', models.ForeignKey(db_column='id_clase', on_delete=django.db.models.deletion.CASCADE, related_name='programaciones', to='academico.clase')),
                ('instructor', models.ForeignKey(db_column='id_instructor', on_delete=django.db.models.deletion.PROTECT, related_name='programaciones', to='docencia.instructor')),
                ('tema', models.ForeignKey(db_column='id_tema', on_delete=django.db.models.deletion.PROTECT, related_name='programaciones', to='docencia.tema')),
            ],
            options={
                'verbose_name': 'Programación de clase',
                'verbose_name_plural': 'Programaciones de clase',
                'db_table': 'programacion_clases',
                'ordering': ['clase', 'numero_semana', 'dia_semana', 'numero_aula'],
            },
        ),
    ]
