# Generated by Django 6.0.7 on 2026-08-05 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academico", "0002_inscripcionestudiante"),
        ("docencia", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgramacionClase",
            fields=[
                (
                    "id_programacion",
                    models.AutoField(
                        db_column="id_programacion", primary_key=True, serialize=False
                    ),
                ),
                ("codigo_clase", models.CharField(max_length=10)),
                ("numero_semana", models.PositiveSmallIntegerField()),
                ("dia_semana", models.CharField(max_length=20)),
                ("numero_aula", models.PositiveSmallIntegerField()),
                (
                    "edicion",
                    models.ForeignKey(
                        db_column="id_edicion",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programaciones",
                        to="academico.edicionescuela",
                    ),
                ),
                (
                    "instructor",
                    models.ForeignKey(
                        db_column="id_instructor",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="programaciones",
                        to="docencia.instructor",
                    ),
                ),
                (
                    "tema",
                    models.ForeignKey(
                        db_column="id_tema",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="programaciones",
                        to="docencia.tema",
                    ),
                ),
            ],
            options={
                "verbose_name": "Programación de clase",
                "verbose_name_plural": "Programaciones de clase",
                "db_table": "programacion_clases",
                "ordering": ["edicion", "numero_semana", "dia_semana", "numero_aula"],
            },
        ),
    ]
