# Generated by Django 6.0.7 on 2026-08-04 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Instructor",
            fields=[
                (
                    "id_instructor",
                    models.AutoField(
                        db_column="id_instructor", primary_key=True, serialize=False
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("apellido", models.CharField(max_length=50)),
                ("cargo", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Instructor",
                "verbose_name_plural": "Instructores",
                "db_table": "instructores",
            },
        ),
        migrations.CreateModel(
            name="Tema",
            fields=[
                (
                    "id_tema",
                    models.AutoField(
                        db_column="id_tema", primary_key=True, serialize=False
                    ),
                ),
                ("titulo_tema", models.CharField(max_length=255)),
                (
                    "activo",
                    models.BooleanField(db_default=True, default=True, null=True),
                ),
            ],
            options={
                "verbose_name": "Tema",
                "verbose_name_plural": "Temas",
                "db_table": "temas",
            },
        ),
    ]
