# Generated by Django 6.0.7 on 2026-08-05 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Clase",
            fields=[
                (
                    "id_clase",
                    models.AutoField(
                        db_column="id_clase", primary_key=True, serialize=False
                    ),
                ),
                ("anio", models.IntegerField()),
                ("nombre", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Clase",
                "verbose_name_plural": "Clases",
                "db_table": "clases",
            },
        ),
        migrations.CreateModel(
            name="EdicionEscuela",
            fields=[
                (
                    "id_edicion",
                    models.AutoField(
                        db_column="id_edicion", primary_key=True, serialize=False
                    ),
                ),
                ("nombre_edicion", models.CharField(max_length=100)),
                ("fecha_inicio", models.DateField(blank=True, null=True)),
                ("fecha_fin", models.DateField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Edición de escuela",
                "verbose_name_plural": "Ediciones de escuela",
                "db_table": "ediciones_escuela",
            },
        ),
    ]
