# Generated by Django 6.0.7 on 2026-08-10 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id_clase', models.AutoField(db_column='id_clase', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
            options={
                'verbose_name': 'Clase',
                'verbose_name_plural': 'Clases',
                'db_table': 'clases',
                'ordering': ['-fecha_inicio', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='InscripcionEstudiante',
            fields=[
                ('id_inscripcion', models.AutoField(db_column='id_inscripcion', primary_key=True, serialize=False)),
                ('clase', models.ForeignKey(db_column='id_clase', on_delete=django.db.models.deletion.PROTECT, related_name='inscripciones', to='academico.clase')),
                ('estudiante', models.ForeignKey(db_column='id_estudiante', on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='estudiantes.estudiante')),
            ],
            options={
                'verbose_name': 'Inscripción de estudiante',
                'verbose_name_plural': 'Inscripciones de estudiantes',
                'db_table': 'inscripciones_estudiantes',
                'constraints': [models.UniqueConstraint(fields=('estudiante', 'clase'), name='uq_estudiante_clase')],
            },
        ),
    ]
