# Generated by Django 6.0.7 on 2026-08-05 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academico", "0001_initial"),
        ("estudiantes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InscripcionEstudiante",
            fields=[
                (
                    "id_inscripcion",
                    models.AutoField(
                        db_column="id_inscripcion", primary_key=True, serialize=False
                    ),
                ),
                (
                    "clase",
                    models.ForeignKey(
                        db_column="id_clase",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inscripciones",
                        to="academico.clase",
                    ),
                ),
                (
                    "edicion",
                    models.ForeignKey(
                        db_column="id_edicion",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inscripciones",
                        to="academico.edicionescuela",
                    ),
                ),
                (
                    "estudiante",
                    models.ForeignKey(
                        db_column="id_estudiante",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inscripciones",
                        to="estudiantes.estudiante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inscripción de estudiante",
                "verbose_name_plural": "Inscripciones de estudiantes",
                "db_table": "inscripciones_estudiantes",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("estudiante", "edicion"), name="uq_estudiante_edicion"
                    )
                ],
            },
        ),
    ]
