# Generated by Django 6.0.7 on 2026-08-05 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academico", "0002_inscripcionestudiante"),
        ("estudiantes", "0001_initial"),
        ("planificacion", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pareja",
            fields=[
                (
                    "id_pareja",
                    models.AutoField(
                        db_column="id_pareja", primary_key=True, serialize=False
                    ),
                ),
                (
                    "clase",
                    models.ForeignKey(
                        db_column="id_clase",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parejas",
                        to="academico.clase",
                    ),
                ),
                (
                    "estudiante_1",
                    models.ForeignKey(
                        db_column="id_estudiante_1",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="parejas_como_estudiante_1",
                        to="estudiantes.estudiante",
                    ),
                ),
                (
                    "estudiante_2",
                    models.ForeignKey(
                        db_column="id_estudiante_2",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="parejas_como_estudiante_2",
                        to="estudiantes.estudiante",
                    ),
                ),
                (
                    "programacion",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_programacion",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="parejas",
                        to="planificacion.programacionclase",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pareja",
                "verbose_name_plural": "Parejas",
                "db_table": "parejas",
            },
        ),
    ]
