# Generated by Django 6.0.7 on 2026-08-09 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pareja',
            options={'ordering': ['clase_id', 'id_pareja'], 'verbose_name': 'Pareja', 'verbose_name_plural': 'Parejas'},
        ),
    ]
